### ISSUE TITLE
can you give your link?

### ISSUE THREAD

**Issue by ENjoy924** [haruto-boshi/GAEE#1]
hello, I look your result and very interest in it , and I want to reference to your paper,can you give me your paper link?thank you very much.

**Comment by haruto-boshi** [comment]
Hi @ENjoy924, I'm glad you're interested in my work. This work was accepted in IEEE CEC 2018, but it still to be published. For this reason I submitted to the ArXiv.org, but I still waiting for the paper id. As soon as I get the paper link I'll sent it you. Feel free to ask any question regarding the work and also I'm curious in what are you working on.

**Comment by haruto-boshi** [comment]
Hi @ENjoy924 , I'm glad you're interested in my work. This work was accepted in IEEE CEC 2018, but it still to be published. For this reason I submitted to the ArXiv.org, here is the link: 

http://arxiv.org/abs/1805.10644 

Feel free to ask any question regarding the work and also I'm curious to know what are you working on.
