### ISSUE TITLE
KeyError: 'X'

### ISSUE THREAD

**Issue by timeons** [haruto-boshi/GAEE#2]
Hello, I'm trying to run the DEMO.py, not getting why it raises error as KeyError: 'X' for both image data and ground truth (KeyError: 'Y') data.

**Comment by haruto-boshi** [comment]
Hi, usually KeyError is due enconding problems. You can solve it by replacing pkg_data['X'] to pkg_data.get('X')  and also pkg_gt['Y'] to pkg_gt.get('Y'). Let me hear back whether you're able to solve it.

**Comment by timeons** [comment]
Thanks for the immediate reply. As per your suggestion, I used pkg_data.get('X')  method to get data, but it is returning None, whose data type is Nonetype.
So can you please help me to resolve this issue.

**Comment by haruto-boshi** [comment]
That's curious, I've just cloned the repository and I got any error. 
I recommend you to create a conda environment and install the requirements in there. Send me more details about your issue so I can reproduce the error.
